# ?????? 117.72.154.85

spring.application.name=Personal_Blog_Backstage
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.configuration.map-underscore-to-camel-case=true
#spring.datasource.url=jdbc:mysql://129.28.26.171:3306/personal_blog
#spring.datasource.url=jdbc:mysql://localhost:3306/personal_blog
# new serve
#spring.datasource.url=jdbc:mysql://222.186.21.30:33306/personal_blog
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/personal_blog
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15

#jdbc:mysql://129.28.26.171:3306
#??? root
spring.datasource.username=33vrKtiEm3EVvRs.root
spring.datasource.password=E6m7Zj3LrXvUWckk
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
server.port=8080

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

logging.level.org.springframework.jdbc.support.jdbcTransactionManager:debug
# application.properties
upload.path=/var/audio-uploads
mybatis.mapper-locations: classpath:mapper/*.xml

#??? OSS
tencent.cos.region=ap-chengdu
tencent.cos.bucket=insande1314520-1328627845
tencent.cos.secretId=AKIDVqzuiNs8AwYu6BAwVpDe0CB3wt2DKDyb
tencent.cos.secretKey=bz8A1snV5ayQp131ugKrFRSN9saCdyBH
#gitee
client_id=5ff53036da534575d2e5306a2761c4eabd3bb9f9b817a33fa5d311ee0c772f4b
client_secret=dd47975fca6ddf19327bca87160d397ea8b64beb2e671104de3c81a12db21d6e
redirect_uri=http://222.186.21.30:8081/giteeLogin
# gitee????
gitee.client_id = 5ff53036da534575d2e5306a2761c4eabd3bb9f9b817a33fa5d311ee0c772f4b
gitee.client_secret = dd47975fca6ddf19327bca87160d397ea8b64beb2e671104de3c81a12db21d6e
gitee.redirectURI = http://117.72.154.85:8081/giteeLogin/callback
gitee.homeURI = http://blog.insand.top
gitee.authorizeURL = https://gitee.com/oauth/authorize
gitee.accessToken = https://gitee.com/oauth/token
gitee.userInfo = https://gitee.com/api/v5/user
#Redis
spring.data.redis.host=117.72.154.85
spring.data.redis.port=6379
spring.data.redis.password=jl1314520

#Redission
spring.redis.redisson.config=classpath:redisson-single-node.yml
